### ISSUE TITLE
Make logging useful

### ISSUE THREAD

**Issue by mtharp** [mtharp/laureline-firmware#1]
The current logging implementation just sends raw data once per second, which isn't very useful. Send "cooked" statistics less frequently, perhaps something similar to what ntpd would send.

**Comment by dorkmatt** [comment]
syslog might be useful here

**Comment by mtharp** [comment]
New loopstats logging is ready to go for next release now that stability issues are resolved.

For what it's worth, syslog was already implemented, see here: http://partiallystapled.com/pub/laureline-docs/config.html#syslog-ip
