### ISSUE TITLE
time of day not set

### ISSUE THREAD

**Issue by albertograti** [mtharp/laureline-firmware#10]
After flashing the bootloader v4.2 and ll.hex (also 4.2) I have the status LED solid yellow and the PPS blinking red for hours. Console output says:
1900-01-01T00:15:43.702180Z vtimer NOTE step(PPS) -197400 us
1900-01-01T00:15:01.899901Z loopstats INFO off:-108570111ns freq:-11844012ppb jit:129443958ns fjit:0ppt looptc:4s state:1 flags:PPS,!ToD,!PLL,!QUANT

**Comment by mtharp** [comment]
If you see lots of step(PPS) it's because you did not set the correct oscillator frequency when you compiled the bootloader. Run "scons dist" and under the "dist" directory you will see 3 bootloaders to choose from, use the one that matches your hardware revision and oscillator frequency.

**Comment by albertograti** [comment]
OK. 26MHz for the 7.0 wasn't in there, but once added in the build list, bootloader-hw7.0-26mhz.elf does the job.
Thanks.
